### ISSUE TITLE
expose versions

### ISSUE THREAD

**Issue by casperdcl** [iterative/setup-tools#1]
expose & forward the individual dep versions.

```yaml
- uses: iterative/setup-tools@v1
    with:
      python-version: '3.x'
      node-version: '16.x'
      cml-version: 'latest'
      dvc-version: 'latest'
```

... and maybe add a cuda & cudnn option? :sweat_smile:
